/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dittl' at '16-6-24 上午1:38' with Gradle 2.14
 *
 * @author dittl, @date 16-6-24 上午1:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
